mod artifact_codecs;
mod continuation_bridge;
mod contracts;
mod history_shape;
mod retention;
mod route_matrix;
mod thread_memory;

pub use artifact_codecs::apply_history_disposition;
pub use artifact_codecs::build_prune_manifest_item;
pub use artifact_codecs::content_items_to_text;
pub use artifact_codecs::prune_superseded_artifacts;
pub use artifact_codecs::remove_artifact_kind;
pub use continuation_bridge::BridgeVariant;
pub use continuation_bridge::ContinuationBridgeModelInput;
pub use continuation_bridge::ContinuationBridgePayload;
pub use continuation_bridge::ContinuationBridgeSourceSelectionInput;
pub use continuation_bridge::ContinuationBridgeSubagentSnapshot;
pub use continuation_bridge::ContinuationBridgeSubagentStatus;
pub use continuation_bridge::PriorBridgeVisibility;
pub use continuation_bridge::build_continuation_bridge_prompt_input;
pub use continuation_bridge::continuation_bridge_output_schema;
pub use continuation_bridge::continuation_bridge_response_item;
pub use continuation_bridge::continuation_bridge_subagent_context_item;
pub use continuation_bridge::default_prompt as continuation_bridge_default_prompt;
pub use continuation_bridge::parse_continuation_bridge_payload;
pub use continuation_bridge::select_continuation_bridge_source;
pub use contracts::ArtifactKind;
pub use contracts::ArtifactLifetime;
pub use contracts::ArtifactRequest;
pub use contracts::ArtifactRequiredness;
pub use contracts::ContextInjectionPolicy;
pub use contracts::GovernanceEffect;
pub use contracts::HistoryDispositionRequest;
pub use contracts::HistoryDispositionResult;
pub use contracts::LegacyCompactionMarkerPolicy;
pub use contracts::MaintenanceAction;
pub use contracts::MaintenancePlanningRequest;
pub use contracts::MaintenancePolicyError;
pub use contracts::MaintenancePolicyPlan;
pub use contracts::MaintenanceTiming;
pub use contracts::PolicyEngine;
pub use contracts::RetentionDirective;
pub use contracts::RetentionGate;
pub use contracts::ThreadMemoryGovernance;
pub use history_shape::RemoteCompactedHistoryShapeRequest;
pub use history_shape::insert_initial_context_before_last_real_user_or_summary;
pub use history_shape::insert_items_before_last_summary_or_compaction;
pub use history_shape::shape_remote_compacted_history;
pub use retention::RetentionApplicationResult;
pub use retention::apply_retention_directive;
pub use retention::retain_recent_raw_conversation_messages;
pub use route_matrix::plan_route;
pub use thread_memory::ThreadMemorySourceSelection;
pub use thread_memory::ThreadMemoryTrimResult;
pub use thread_memory::build_thread_memory_update_message;
pub use thread_memory::limit_thread_memory_source_items;
pub use thread_memory::parse_thread_memory_payload;
pub use thread_memory::split_previous_memory_and_source_items;
pub use thread_memory::thread_memory_output_schema;
pub use thread_memory::thread_memory_response_item;

#[cfg(test)]
mod tests;
