//! Semantic owner for prompt-ingress schema selection and active packet rendering.

mod adjudicator;
mod candidates;
mod packet;
mod registry;
mod render;

pub use adjudicator::BrokerResolution;
pub use adjudicator::BrokerWitness;
pub use adjudicator::ClarifyDisposition;
pub use adjudicator::DeterministicAdjudicator;
pub use adjudicator::ResolutionConfidence;
pub use adjudicator::SchemaAdjudicator;
pub use adjudicator::adjudicate_candidates;
pub use candidates::BrokerInput;
pub use candidates::CandidateNarrowingWitness;
pub use candidates::CandidateSet;
pub use candidates::ExcludedCandidateReason;
pub use candidates::ExcludedSchemaCandidate;
pub use candidates::SchemaCandidate;
pub use candidates::build_candidate_set;
pub use packet::ACTIVE_CONTEXT_PACKET_SCHEMA;
pub use packet::ACTIVE_CONTEXT_PACKET_TAG;
pub use packet::ActiveContextPacket;
pub use packet::BrokerResolutionSummary;
pub use packet::ConfidenceDecision;
pub use packet::LexicalEvolutionEvent;
pub use packet::PacketBudget;
pub use packet::PacketId;
pub use packet::ResolvedOperatorRef;
pub use packet::ResolvedSchemaRef;
pub use packet::build_active_context_packet;
pub use registry::AliasTarget;
pub use registry::CanonicalOperator;
pub use registry::OperatorId;
pub use registry::RegisteredOperator;
pub use registry::RegisteredSchema;
pub use registry::RegistryConflictKind;
pub use registry::RegistryConflictResolution;
pub use registry::RegistrySnapshotError;
pub use registry::RegistrySource;
pub use registry::RegistrySourceFamily;
pub use registry::RegistryVersion;
pub use registry::SchemaAlias;
pub use registry::SchemaId;
pub use registry::SchemaRegistrySnapshot;
pub use registry::build_v0_registry_snapshot;
pub use registry::builtin_registry;
pub use render::is_active_context_packet_text;
pub use render::render_active_context_packet;
pub use render::render_active_context_packet_item;
